---
title: "R Notebook"
output: html_notebook
---


```{r}

library(VLTimeCausality)
count0<-0
count1<-0
for(i in seq(10))
{ 
  x1<-rnorm(200,0,1)
  x2<-rnorm(200,0,1)
  out0<-SimpleSimulationVLtimeseries()
  x1<-out0$y
  x2<-out0$x
#a<-SimpleSimulationVLtimeseries()
#b<-SimpleSimulationVLtimeseries()

A<-VLGrangerFunc(Y=x1,X=x2,alpha=0.05)
VLGdiffRatio<-A$BICDiffRatio
count0<-count0 + as.integer( VLGdiffRatio>=0.5 )

print(sprintf("i%d",i) )
print(VLGdiffRatio)
print(A$p.val)
print(Foll$VLval)
}
print(sprintf("VLcount%d",count0))
```
TEST
=====
```{r}
TS<-MultipleSimulationVLtimeseries()
out<-multipleVLGrangerFunc(TS)$adjMat
checkMultipleSimulationVLtimeseries(out)
```


.....
```{r}
#set.seed(20180108)
library(VLTimeCausality)

# countH0<-0.0
# countH1<-0.0
# countHcomp<-0.0
countDiff<-0
n <- 200
L<-5

diffVec0<-numeric(100)
diffVec1<-numeric(100)

for (k in seq(100))
{
  print(k)
# x <- rep(0, n + L)
# y <- rep(0, n + L)
# 
# 
# for (i in seq(n)) {
#   x[i + 1] <- 0.2 * x[i] + rnorm(1, 0, 2)
#   y[i + L] <- x[i] + rnorm(1, 0, 0.5)
# }
# 
# y[111:150]<-x[100]
# 
# x <- x[-(1:L)]
# y <- y[-(1:L)]
out1<-VLTimeCausality::SimpleSimulationVLtimeseries()
x<-out1$x
y<-out1$y

M0<-GrangerFunc(Y=y,X=x, maxLag=5) 
M1<-VLGrangerFunc(Y=y,X=x, maxLag=5) 
VLGdiff<-M1$BIC_H0-M1$BIC_H1
Gdiff<-M0$BIC_H0-M0$BIC_H1

countDiff<- countDiff + as.integer(Gdiff<VLGdiff)
diffVec0[k]<-Gdiff
diffVec1[k]<-VLGdiff
}
countDiff

```
#result
```{r}
#load("VLGresult.RData")
library(ggplot2)


dat <- data.frame(dens = c(diffVec0, diffVec1)
                   , lines = rep(c("Granger", "VL-Granger"), each = 100))
#Plot.
theme_update(text = element_text( size=20)  )
p1<-ggplot(dat, aes(x = dens, fill = lines)) + geom_density(alpha = 0.5) + xlab("BIC difference") +ylab("Density [0,1]") + theme_light()+theme( axis.text.x = element_text(
                                      size=20, angle=45), axis.text.y = element_text(  
                                      size=20), text = element_text(size=20) )

p1$labels$fill<-"Methods"
plot(p1)
```

#Experiment
```{r}
autoLagflag<-TRUE
maxLag<-round(0.1*200)
option0<-0
```


Part1

```{r}
library(rmatio)
count2<-0
for(i in seq(100))
{
filename<-sprintf("data/SimData/SimTrajectoryDir-NORMAL-FOLL-%d.mat",i)
out<-read.mat(filename)
option=option0
flag<-FALSE
if(option==0)
{
  B<-VLGrangerFunc(Y=out$Y,X=out$L,gamma=0.5 ,autoLagflag=autoLagflag,maxLag=maxLag)
  print(sprintf("i%d,BICdr%f",i,B$BICDiffRatio) )
  flag<- B$XgCsY
}
else if(option==1)
{
  B<-VLTransferEntropy(Y=out$Y,X=out$L,VLflag=FALSE,maxLag=maxLag,lx=maxLag,ly=maxLag,autoLagflag=autoLagflag)
  flag<-B$XgCsY_trns
  print(sprintf("i%d,TFratio%f",i,B$TEratio) )
}
else if(option==2)
{
  B<-VLTransferEntropy(Y=out$Y,X=out$L,VLflag=TRUE,maxLag=maxLag,lx=maxLag,ly=maxLag,autoLagflag=autoLagflag)
  flag<-B$XgCsY_trns
  print(sprintf("i%d,TFratio%f",i,B$TEratio) )
}

count2<-count2+as.integer( flag )
}
count2
```

```{r}
library(rmatio)
count3<-0
for(i in seq(100))
{
filename<-sprintf("data/SimData/SimTrajectoryDir-NORMAL-NORMAL-%d.mat",i)
out<-read.mat(filename)
option=option0
flag<-FALSE
if(option==0)
{
  B<-VLGrangerFunc(Y=out$Y,X=out$L,gamma=0.5,autoLagflag=autoLagflag,maxLag=maxLag)
  print(sprintf("i%d,BICdr%f",i,B$BICDiffRatio) )
  flag<- B$XgCsY
}
else if(option==1)
{
  B<-VLTransferEntropy(Y=out$Y,X=out$L,VLflag=FALSE,maxLag=maxLag,lx=maxLag,ly=maxLag,autoLagflag=autoLagflag)
  flag<-B$XgCsY_trns
  print(sprintf("i%d,TFratio%f",i,B$TEratio) )
}
else if(option==2)
{
  B<-VLTransferEntropy(Y=out$Y,X=out$L,VLflag=TRUE,maxLag=maxLag,lx=maxLag,ly=maxLag,autoLagflag=autoLagflag)
  flag<-B$XgCsY_trns
  print(sprintf("i%d,TFratio%f",i,B$TEratio) )
}


count3<-count3+as.integer( flag )
}
count3
```

```{r}
library(rmatio)
count4<-0
for(i in seq(100))
{
filename<-sprintf("data/SimData/SimTrajectoryDir-ARMA-FOLL-%d.mat",i)
out<-read.mat(filename)
option=option0
flag<-FALSE
if(option==0)
{
  B<-VLGrangerFunc(Y=out$Y,X=out$L,gamma=0.5,autoLagflag=autoLagflag,maxLag=maxLag)
  print(sprintf("i%d,BICdr%f",i,B$BICDiffRatio) )
  flag<- B$XgCsY
}
else if(option==1)
{
  B<-VLTransferEntropy(Y=out$Y,X=out$L,VLflag=FALSE,maxLag=maxLag,lx=maxLag,ly=maxLag,autoLagflag=autoLagflag)
  flag<-B$XgCsY_trns
  print(sprintf("i%d,TFratio%f",i,B$TEratio) )
}
else if(option==2)
{
  B<-VLTransferEntropy(Y=out$Y,X=out$L,VLflag=TRUE,maxLag=maxLag,lx=maxLag,ly=maxLag,autoLagflag=autoLagflag)
  flag<-B$XgCsY_trns
  print(sprintf("i%d,TFratio%f",i,B$TEratio) )
}


count4<-count4+as.integer( flag )
}
count4
```

```{r}
library(rmatio)
count5<-0
for(i in seq(100))
{
filename<-sprintf("data/SimData/SimTrajectoryDir-ARMA-ARMA-%d.mat",i)
out<-read.mat(filename)
option=option0
flag<-FALSE
if(option==0)
{
  B<-VLGrangerFunc(Y=out$Y,X=out$L,gamma=0.5,autoLagflag=autoLagflag,maxLag=maxLag)
  print(sprintf("i%d,BICdr%f",i,B$BICDiffRatio) )
  flag<- B$XgCsY
}
else if(option==1)
{
  B<-VLTransferEntropy(Y=out$Y,X=out$L,VLflag=FALSE,maxLag=maxLag,lx=maxLag,ly=maxLag,autoLagflag=autoLagflag)
  flag<-B$XgCsY_trns
  print(sprintf("i%d,TFratio%f",i,B$TEratio) )
}
else if(option==2)
{
  B<-VLTransferEntropy(Y=out$Y,X=out$L,VLflag=TRUE,maxLag=maxLag,lx=maxLag,ly=maxLag,autoLagflag=autoLagflag)
  flag<-B$XgCsY_trns
  print(sprintf("i%d,TFratio%f",i,B$TEratio) )
}

count5<-count5+as.integer( flag )
}
count5
```

```{r}
library(rmatio)
count6<-0
for(i in seq(100))
{
filename<-sprintf("data/SimData/SimTrajectoryDir-ARMA-NORMAL-%d.mat",i)
out<-read.mat(filename)
option=option0
flag<-FALSE
if(option==0)
{
  B<-VLGrangerFunc(Y=out$Y,X=out$L,gamma=0.5,autoLagflag=autoLagflag,maxLag=maxLag)
  print(sprintf("i%d,BICdr%f",i,B$BICDiffRatio) )
  flag<- B$XgCsY
}
else if(option==1)
{
  B<-VLTransferEntropy(Y=out$Y,X=out$L,VLflag=FALSE,maxLag=maxLag,lx=maxLag,ly=maxLag,autoLagflag=autoLagflag)
  flag<-B$XgCsY_trns
  print(sprintf("i%d,TFratio%f",i,B$TEratio) )
}
else if(option==2)
{
  B<-VLTransferEntropy(Y=out$Y,X=out$L,VLflag=TRUE,maxLag=maxLag,lx=maxLag,ly=maxLag,autoLagflag=autoLagflag)
  flag<-B$XgCsY_trns
  print(sprintf("i%d,TFratio%f",i,B$TEratio) )
}


count6<-count5+as.integer( flag )
}
count6
```

